### ISSUE TITLE
Catalyst CLI fails to fails at graphql schema generation

### ISSUE THREAD

**Issue by AndrewBarber** [bigcommerce/catalyst#675]
> We really appreciate the help making Catalyst better. Every issue helps!

No problem! 🙌 

**Describe the bug**
When running catalyst-cli to setup and connect to a store, an error is received and the setup does not complete.

The error is as follows:
```
➜  Learning npm create catalyst-storefront@latest


◢ @bigcommerce/create-catalyst v0.1.0

? What is the name of your project? catalyst-training
? Would you like to connect to a BigCommerce store? Yes

Please visit https://login.bigcommerce.com/device/connect and enter the code: mf3ftjeh

The code will expire in 30 minutes

✔ Device code authorized

You have reached the maximum number of active storefronts allowed for your plan. Please select an existing channel below, de-activate an active channel, or purchase additional storefront seats in your BigCommerce Control Panel.

? Which channel would you like to use? catalyst

Creating 'catalyst-training' at '/Users/andrew/Developer/Learning/catalyst-training'

✔ Catalyst template cloned successfully
✔ Catalyst components cloned successfully

Using npm

✔ Dependencies installed successfully
✖ Failed to generate GraphQL types: Command failed: npm run codegen
[FAILED]
[FAILED]         Failed to load schema from ./schema.graphql:
[FAILED]
[FAILED]
[FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[FAILED]
[FAILED]           - ./schema.graphql
[FAILED]
[FAILED]         Error:
[FAILED]       Unable to find any GraphQL type definitions for the following pointers:
[FAILED]
[FAILED]           - ./schema.graphql
[FAILED]
[FAILED]     at prepareResult (/Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-tools/load/cjs/load-typedefs.js:82:15)
[FAILED]     at loadTypedefs (/Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-tools/load/cjs/load-typedefs.js:40:20)
[FAILED]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[FAILED]     at async loadSchema (/Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-tools/load/cjs/schema.js:15:21)
[FAILED]     at async loadSchema (/Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-codegen/cli/cjs/load.js:36:24)
[FAILED]     at async /Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-codegen/cli/cjs/codegen.js:190:69
[FAILED]     at async /Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-codegen/cli/cjs/codegen.js:189:56
[FAILED]     at async /Users/andrew/Developer/Learning/catalyst-training/node_modules/@graphql-codegen/cli/cjs/codegen.js:66:17
[FAILED]     at async Task.run (/Users/andrew/Developer/Learning/catalyst-training/node_modules/listr2/dist/index.cjs:979:11)
[FAILED]     at async /Users/andrew/Developer/Learning/catalyst-training/node_modules/p-map/index.js:57:22
[FAILED]
[FAILED]         GraphQL Code Generator supports:
[FAILED]           - ES Modules and CommonJS exports (export as default or named export "schema")
[FAILED]           - Introspection JSON File
[FAILED]           - URL of GraphQL endpoint
[FAILED]           - Multiple files with type definitions (glob expression)
[FAILED]           - String in config file
[FAILED]
[FAILED]         Try to use one of above options and run codegen again.
[FAILED]
[FAILED]

npm ERR! code 1
npm ERR! path /Users/andrew/Developer/Learning
npm ERR! command failed
npm ERR! command sh -c create-catalyst-storefront
```
**To Reproduce**
1. `nvm use 18.18.1` (also same on 21.6.2)
2. `npm create catalyst-storefront@latest`
3. Follow prompts - attaching to a store

**Expected behavior**
Local theme should generate correctly

**Screenshots**
![Screenshot 2024-03-19 at 16 56 29](https://github.com/bigcommerce/catalyst/assets/135927/a1c379dc-a600-4d8a-a07e-3e921589a577)

**Additional context**
Store hash is `jk0h5oo6h0`

**Comment by christensenep** [comment]
Thank you for the report @AndrewBarber, and apologies that you ran into that issue. This has now been fixed in the latest release of the Catalyst CLI we pushed out just now. Note however that the command to run the CLI is now `npm create @bigcommerce/catalyst@latest`.
