### ISSUE TITLE
'npm run dev' Catalyst encountered problems with GraphQL

### ISSUE THREAD

**Issue by nguyenphuochien97** [bigcommerce/catalyst#682]
I have an issue when I run the command 'npm run dev'

I use Node v20.11.1

My issues:

```
[next] [BigCommerce] KV MGET - Keys: g5ps0j2lj8_1_v3_/,g5ps0j2lj8_1_storeStatus - Value: [
[next]   null,
[next]   null
[next] ]
[next]  [GraphQLError: Syntax Error: Unexpected "[".] {
[next]   message: 'Syntax Error: Unexpected "[".',
[next]   path: undefined,
[next]   locations: [ { line: 1, column: 1 } ],
[next]   extensions: [Object: null prototype] {}
[next] }
[next]  ○ Compiling /[locale]/static ...
[next]  ✓ Compiled /[locale]/static in 7.3s (3572 modules)
[next]  ✓ Compiled in 510ms (1368 modules)
[next] [BigCommerce] query getWebPages - 106ms - complexity 1073
[next] [BigCommerce] query getFeaturedProducts - 91ms - complexity 1313
[next] [BigCommerce] query getNewestProducts - 93ms - complexity 1313
[next] [BigCommerce] query getFeaturedProducts - 91ms - complexity 1310
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-brands.ts:33:66)
[next]     at BrandFooterMenu (./components/footer/footer-menus/brand-footer-menu.tsx:13:95)
[next]     at stringify (<anonymous>)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] digest: "783364282"
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-category-tree.ts:39:66)
[next]     at async CategoryFooterMenu (./components/footer/footer-menus/category-footer-menu.tsx:13:26)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-category-tree.ts:39:66)
[next]     at async CategoryFooterMenu (./components/footer/footer-menus/category-footer-menu.tsx:13:26)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-category-tree.ts:39:66)
[next]     at async CategoryFooterMenu (./components/footer/footer-menus/category-footer-menu.tsx:13:26)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] digest: "783364282"
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-category-tree.ts:39:66)
[next]     at async CategoryFooterMenu (./components/footer/footer-menus/category-footer-menu.tsx:13:26)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-brands.ts:33:66)
[next]     at BrandFooterMenu (./components/footer/footer-menus/brand-footer-menu.tsx:13:95)
[next]     at stringify (<anonymous>)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-category-tree.ts:39:66)
[next]     at async CategoryFooterMenu (./components/footer/footer-menus/category-footer-menu.tsx:13:26)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-store-settings.ts:47:66)
[next]     at Module.generateMetadata (./app/[locale]/layout.tsx:31:117)
[next] null
[next]  ⨯ node_modules\graphql\error\syntaxError.mjs (8:0) @ syntaxError
[next]  ⨯ GraphQLError: Syntax Error: Unexpected "[".
[next]     at eval (./client/queries/get-category-tree.ts:39:66)
[next]     at async CategoryFooterMenu (./components/footer/footer-menus/category-footer-menu.tsx:13:26)
[next] null
```

Screenshots:

![image](https://github.com/bigcommerce/catalyst/assets/137053650/f79bdb3b-d926-464d-bfda-1d69d330f2be)

![image](https://github.com/bigcommerce/catalyst/assets/137053650/0b6ac822-7fb9-43a8-8d7f-e409ca025933)

Thank you,

DukehNG

**Comment by chanceaclark** [comment]
Hey @nguyenphuochien97, thanks for raising this issue!

We looked into it and looks like our `@bigcommerce/catalyst-client` didn't get published with the changes this newer code needed. We are going to release a new version (`0.2.0`) which should fix this issue.

**Comment by nguyenphuochien97** [comment]
> Hey @nguyenphuochien97, thanks for raising this issue!
> 
> We looked into it and looks like our `@bigcommerce/catalyst-client` didn't get published with the changes this newer code needed. We are going to release a new version (`0.2.0`) which should fix this issue.

Hi team, thanks for the quick response!

The problem has been resolved.
