### ISSUE TITLE
Login is not working when on version 0.5.0

### ISSUE THREAD

**Issue by tomzweb** [bigcommerce/catalyst#752]
On Catalyst version 0.5.0, it is not possible to log in locally (not tested on Vercel). I've tested the same store and same login details on version 0.4.0 locally and it logs in successfully and I'm able to view the account page.

Steps to reproduce the behaviour:

1. Install and setup bigcommerce/catalyst 0.5.0
2. Run npm run dev
3. Visit /login and attempt to login with a valid user
4. Nothing happens, you are not logged in, there's no error on the page and you remain on /login

After clicking 'Log in', the logs show the below:

```
[BigCommerce] KV MGET - Keys: storeHash_1_v3_/login/,storeHash_1_storeStatus - Value: [
  {
    "route": {
      "redirect": null,
      "node": null
    },
    "expiryTime": 1712916600782
  },
  {
    "status": "LAUNCHED",
    "expiryTime": 1712915100579
  }
]
[BigCommerce] mutation Login - 945ms - complexity 9999
[BigCommerce] KV MGET - Keys: storeHash_1_v3_/account/,storeHash_1_storeStatus - Value: [
  null,
  {
    "status": "LAUNCHED",
    "expiryTime": 1712915100579
  }
]
[BigCommerce] query getRoute - 254ms - complexity 1009
[BigCommerce] KV SET - Key: storeHash_1_v3_/account/ - Value: {
  "route": {
    "redirect": null,
    "node": null
  },
  "expiryTime": 1712916627343
}
[BigCommerce] query RootLayoutMetadataQuery - 3ms - complexity 1002
 ⨯ Error [TypeError]: Invalid URL
    at new NodeError (node:internal/errors:405:5)
    at new URL (node:internal/url:611:13)
    at parseURL (webpack-internal:///(ssr)/./node_modules/next/dist/esm/server/web/next-url.js:15:12)
    at new NextURL (webpack-internal:///(ssr)/./node_modules/next/dist/esm/server/web/next-url.js:29:18)
    at adapter (webpack-internal:///(ssr)/./node_modules/next/dist/esm/server/web/adapter.js:220:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async (<removed>/node_modules/next/dist/server/web/sandbox/sandbox.js:110:22)
    at async runWithTaggedErrors (<removed>/node_modules/next/dist/server/web/sandbox/sandbox.js:107:9)
    at async DevServer.runEdgeFunction (<removed>/node_modules/next/dist/server/next-server.js:1199:24)
    at async NextNodeServer.handleCatchallRenderRequest (<removed>/node_modules/next/dist/server/next-server.js:248:37)
    at async DevServer.handleRequestImpl (<removed>/node_modules/next/dist/server/base-server.js:811:17)
    at async (<removed>/node_modules/next/dist/server/dev/next-dev-server.js:339:20)
    at async Span.traceAsyncFn (<removed>/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (<removed>/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async invokeRender (<removed>/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (<removed>/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (<removed>/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (<removed>/node_modules/next/dist/server/lib/start-server.js:141:13)
[BigCommerce] query NotFoundQuery - 0ms - complexity 5692
 POST /login/ 500 in 1632ms
 POST /login/ 500 in 1614ms
[BigCommerce] query LayoutQuery - 328ms - complexity 4383
 GET /account/ 200 in 939ms
 GET /account/ 200 in 660ms
```

On the working 0.4.0 version, after clicking 'Log in' the logs show the below and you're redirected to the /account page.

```[BigCommerce] KV MGET - Keys: storeHash_1_v3_/login/,storeHash_1_storeStatus - Value: [
  {
    "route": {
      "redirect": null,
      "node": null
    },
    "expiryTime": 1712916267618
  },
  {
    "status": "LAUNCHED",
    "expiryTime": 1712915753912
  }
]
[BigCommerce] mutation Login - 777ms - complexity 9999
[BigCommerce] KV MGET - Keys: storeHash_1_v3_/account/,storeHash_1_storeStatus - Value: [
  {
    "route": {
      "redirect": null,
      "node": null
    },
    "expiryTime": 1712916277772
  },
  {
    "status": "LAUNCHED",
    "expiryTime": 1712915753912
  }
]
[BigCommerce] query RootLayoutMetadataQuery - 2ms - complexity 1002
[BigCommerce] query NotFoundQuery - 1ms - complexity 5692
[BigCommerce] query LayoutQuery - 373ms - complexity 4383```

**Comment by deini** [comment]
@tomzweb Thanks for reporting this. Please try downgrading next to `14.1.4` while we investigate.

**Comment by deini** [comment]
This go auto-closed. Should remain open until https://github.com/bigcommerce/catalyst/pull/756 gets merged
